server:
  port: 8081

spring:
  application:
    name: eureka-service # 微服务的名称
  activemq: # 配置activeMq
    broker-url: tcp://192.168.88.132:61616 # activeMq的服务地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false = Queue true = topic
  redis: #配置redis
    host: 192.168.88.128
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 1200
  datasource: #配置jdbc
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 自己定义的队列名称
myQueue: boot-activemq-queue
# 自己的topic名称
myTopic: boot-acitvemq-topic

eureka:
  client:
    service-url:
      defaultZone: http://192.168.88.128:8888/eureka/, http://192.168.88.129:8888/eureka
