server:
  port: 8081

spring:
  application:
    name: eureka-service # 微服务的名称
  activemq: # 配置activeMq
    broker-url: tcp://192.168.88.132:61616 # activeMq的服务地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false = Queue true = topic
# 自己定义的队列名称
myQueue: boot-activemq-queue
# 自己的topic名称
myTopic: boot-acitvemq-topic

eureka:
  client:
    service-url:
      defaultZone: http://192.168.88.128:8888/eureka/, http://192.168.88.129:8888/eureka
