server:
  port: 8888

spring:
  application:
    name: eureka-service # 微服务的名称
  activemq: # 配置activeMq
    broker-url: tcp://192.168.244.128:61616 # activeMq的服务地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false = Queue true = topic
  redis: #配置redis
    host: 39.99.198.219
    port: 6379
    password:
    database: 0
  datasource: #配置jdbc
    url: jdbc:mysql://39.99.198.219:3306/test?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
# 自己定义的队列名称
myQueue: boot-activemq-queue
# 自己的topic名称
myTopic: boot-acitvemq-topic

eureka:
  client:
    service-url:
      defaultZone: http://192.168.244.128:8888/eureka/, http://192.168.88.129:8888/eureka

# hadoop配置
hadoop:
  URL: hdfs://39.99.198.219:9000
  user: root